version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/ktbv2
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:80"  # Serve frontend on port 80
    depends_on:
      - backend  # Ensure backend starts before frontend

  backend:
    build:
      context: ./backend/ktbv2
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"  # Expose Django on port 8000
    volumes:
      - ./backend/ktbv2:/app
    # network_mode: "host"  # Add this line
    

# Optionally, you can define a custom network if needed, but this is not necessary for simple setups
