# Generated by Django 5.0.7 on 2024-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='date')),
                ('per_each', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Additive',
                'verbose_name_plural': 'Additives',
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('name', models.CharField(max_length=50)),
                ('per_each', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packings',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost_per_liter', models.FloatField()),
                ('buy_price_pmt', models.FloatField()),
                ('add_cost', models.FloatField()),
                ('total', models.FloatField()),
                ('ml_to_kl', models.FloatField()),
                ('density', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'RawMaterial',
                'verbose_name_plural': 'RawMaterials',
            },
        ),
    ]
