# Generated by Django 5.0.7 on 2026-02-27 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('sae', models.CharField(max_length=50)),
                ('net_blending_qty', models.FloatField()),
                ('gross_vol_crosscheck', models.FloatField()),
                ('cross_check', models.FloatField()),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('per_litre_cost', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Consumption',
                'verbose_name_plural': 'Consumptions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('sae', models.CharField(max_length=50)),
                ('ref', models.CharField(editable=False, max_length=50, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Consumption',
                'verbose_name_plural': 'Consumptions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('name', models.CharField(max_length=50)),
                ('per_each', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PackingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bottles_per_pack', models.CharField(max_length=10)),
                ('litres_per_pack', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PackingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'PackingType',
                'verbose_name_plural': 'PackingTypes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_name', models.CharField(max_length=100)),
                ('consumption_name', models.CharField(max_length=100)),
                ('consumption_qty', models.FloatField()),
                ('packing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'ProductFormula',
                'verbose_name_plural': 'ProductFormulas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdditiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='costmgt.additivecategory')),
            ],
            options={
                'verbose_name': 'AdditiveCategory',
                'verbose_name_plural': 'AdditiveCategories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('crfPrice', models.FloatField()),
                ('addCost', models.FloatField()),
                ('costPriceInLiter', models.FloatField()),
                ('density', models.FloatField()),
                ('totalCost', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additives', to='costmgt.additivecategory')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additives_name', to='costmgt.additivecategory')),
            ],
            options={
                'verbose_name': 'Additive',
                'verbose_name_plural': 'Additives',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdditiveExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='costmgt.additive')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='costmgt.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_name', models.CharField(max_length=50)),
                ('qty_in_percent', models.FloatField()),
                ('qty_in_litre', models.FloatField()),
                ('value', models.FloatField()),
                ('rate', models.FloatField()),
                ('consumption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmgt.consumption')),
            ],
            options={
                'verbose_name': 'ConsumptionAdditive',
                'verbose_name_plural': 'ConsumptionAdditives',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionBaseOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_name', models.CharField(max_length=50)),
                ('qty_in_percent', models.FloatField()),
                ('qty_in_litre', models.FloatField()),
                ('value', models.FloatField()),
                ('rate', models.FloatField()),
                ('consumption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmgt.consumption')),
            ],
            options={
                'verbose_name': 'ConsumptionBaseOil',
                'verbose_name_plural': 'ConsumptionBaseOils',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionFormulaAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qty_in_percent', models.FloatField()),
                ('consumption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmgt.consumptionformula')),
            ],
            options={
                'verbose_name': 'ConsumptionFormulaAdditive',
                'verbose_name_plural': 'ConsumptionFormulaAdditives',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionFormulaBaseOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qty_in_percent', models.FloatField()),
                ('consumption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costmgt.consumptionformula')),
            ],
            options={
                'verbose_name': 'ConsumptionFormulaBaseOil',
                'verbose_name_plural': 'ConsumptionFormulaBaseOils',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FinalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('bottles_per_pack', models.FloatField(blank=True, null=True)),
                ('litres_per_pack', models.FloatField(blank=True, null=True)),
                ('total_qty', models.FloatField(blank=True, null=True)),
                ('total_qty_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_in_litres', models.FloatField(blank=True, null=True)),
                ('total_oil_consumed', models.FloatField(blank=True, null=True)),
                ('per_litre_cost', models.FloatField(blank=True, null=True)),
                ('total_cfr_pricing', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_product', to='costmgt.consumption')),
                ('packing_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_product', to='costmgt.packingsize')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_product', to='costmgt.productformula')),
            ],
        ),
        migrations.CreateModel(
            name='FinalProductAdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='costmgt.finalproduct')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FinalProductPackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type', models.CharField(max_length=100)),
                ('packing', models.CharField(max_length=100)),
                ('qty', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='costmgt.finalproduct')),
                ('selected_packing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_product_item', to='costmgt.packing')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PackingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='costmgt.packing')),
            ],
        ),
        migrations.AddField(
            model_name='packing',
            name='packing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packings', to='costmgt.packingtype'),
        ),
        migrations.CreateModel(
            name='ProductFormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type', models.CharField(max_length=100)),
                ('packing_label', models.CharField(max_length=100)),
                ('qty', models.FloatField()),
                ('product_formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_formula_items', to='costmgt.productformula')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RawCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='costmgt.rawcategory')),
            ],
            options={
                'verbose_name': 'RawCategory',
                'verbose_name_plural': 'RawCategories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('cost_per_liter', models.FloatField(blank=True, null=True)),
                ('buy_price_pmt', models.FloatField(blank=True, null=True)),
                ('add_cost', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('ml_to_kl', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawmaterials', to='costmgt.rawcategory')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawmaterials_name', to='costmgt.rawcategory')),
            ],
            options={
                'verbose_name': 'RawMaterial',
                'verbose_name_plural': 'RawMaterials',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RMExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='costmgt.rawmaterial')),
            ],
        ),
    ]
