# Generated by Django 5.0.7 on 2024-09-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costmgt', '0002_consumption_consumptionadditive_consumptionbaseoil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumptionadditive',
            old_name='product',
            new_name='consumption',
        ),
        migrations.RenameField(
            model_name='consumptionbaseoil',
            old_name='product',
            new_name='consumption',
        ),
    ]
