# Generated by Django 5.0.7 on 2024-09-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costmgt', '0003_rename_product_consumptionadditive_consumption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('packing_size', models.CharField(blank=True, max_length=50, null=True)),
                ('bottles_per_pack', models.FloatField(blank=True, null=True)),
                ('liters_per_pack', models.FloatField(blank=True, null=True)),
                ('total_qty', models.FloatField(blank=True, null=True)),
                ('total_qty_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_in_liters', models.FloatField(blank=True, null=True)),
                ('per_liter_cost', models.FloatField(blank=True, null=True)),
                ('cost_per_case', models.FloatField(blank=True, null=True)),
                ('dk_cost', models.FloatField(blank=True, null=True)),
                ('price_per_bottle', models.CharField(max_length=50, verbose_name='price_per_bottle')),
                ('price_per_label', models.CharField(max_length=50, verbose_name='price_per_label')),
                ('price_per_bottle_cap', models.CharField(max_length=50, verbose_name='price_per_bottle_cap')),
                ('bottle_per_case', models.FloatField(verbose_name='bottle_per_case')),
                ('label_per_case', models.FloatField(verbose_name='label_per_case')),
                ('bottle_cap_per_case', models.FloatField(verbose_name='bottle_cap_per_case')),
                ('price_per_carton', models.CharField(max_length=50, verbose_name='price_per_carton')),
                ('dk_exprice', models.FloatField(blank=True, null=True)),
                ('ks_cost', models.FloatField(blank=True, null=True)),
                ('total_factory_price', models.FloatField(blank=True, null=True)),
                ('freight_logistic', models.FloatField(blank=True, null=True)),
                ('total_cif_price', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'FinalProduct',
                'verbose_name_plural': 'FinalProducts',
            },
        ),
    ]
