# Generated by Django 5.0.7 on 2024-07-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepayment',
            name='trn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trademgt.trade', verbose_name='trn'),
        ),
        migrations.AlterField(
            model_name='presalepurchase',
            name='trn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trademgt.trade', verbose_name='trn'),
        ),
    ]
