# Generated by Django 5.0.7 on 2024-09-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presalepurchase',
            name='advance_due_date',
        ),
        migrations.RemoveField(
            model_name='presalepurchase',
            name='lc_due_date',
        ),
        migrations.RemoveField(
            model_name='presalepurchase',
            name='payment_term',
        ),
        migrations.CreateModel(
            name='PreDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('presalepurchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trademgt.presalepurchase', verbose_name='presalepurchase')),
            ],
            options={
                'verbose_name': 'PreDocument',
                'verbose_name_plural': 'PreDocuments',
            },
        ),
    ]
