# Generated by Django 5.0.7 on 2024-08-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0002_alter_prepayment_trn_alter_presalepurchase_trn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='approved_by'),
        ),
    ]
