# Generated by Django 5.0.7 on 2024-08-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0003_alter_trade_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeextracost',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_extra_costs', to='trademgt.trade'),
        ),
        migrations.AlterField(
            model_name='tradeproduct',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_products', to='trademgt.trade'),
        ),
    ]
