# Generated by Django 5.0.7 on 2024-08-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0004_alter_tradeextracost_trade_alter_tradeproduct_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespurchase',
            name='production_date',
            field=models.DateField(verbose_name='production_date'),
        ),
    ]
