# Generated by Django 5.0.7 on 2024-08-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0005_alter_salespurchase_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespurchaseextracharge',
            name='charge',
            field=models.FloatField(null=True, verbose_name='charge'),
        ),
    ]
