# Generated by Django 5.0.7 on 2024-08-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0006_alter_salespurchaseextracharge_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespurchaseextracharge',
            name='charge',
            field=models.FloatField(blank=True, null=True, verbose_name='charge'),
        ),
    ]
