# Generated by Django 5.0.7 on 2024-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0007_alter_salespurchaseextracharge_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='related_trades',
            field=models.ManyToManyField(blank=True, related_name='related_trades', to='trademgt.trade'),
        ),
    ]
