# Generated by Django 5.0.7 on 2024-08-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0008_trade_related_trades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='related_trades',
            new_name='related_trade',
        ),
    ]
