# Generated by Django 5.0.7 on 2024-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0010_rename_related_trade_trade_related_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('companyRegNo', models.CharField(max_length=255)),
                ('regAddress', models.CharField(max_length=255)),
                ('mailingAddress', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('person1', models.CharField(max_length=255)),
                ('designation1', models.CharField(max_length=255)),
                ('mobile1', models.CharField(max_length=255)),
                ('email1', models.CharField(max_length=255)),
                ('person2', models.CharField(max_length=255)),
                ('designation2', models.CharField(max_length=255)),
                ('mobile2', models.CharField(max_length=255)),
                ('email2', models.CharField(max_length=255)),
                ('banker', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('swiftCode', models.CharField(blank=True, max_length=255, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('approve1', models.BooleanField(default=False)),
                ('approve2', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Kyc',
                'verbose_name_plural': 'Kycs',
            },
        ),
    ]
