# Generated by Django 5.0.7 on 2024-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0011_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn', models.CharField(max_length=50, verbose_name='trn')),
                ('trd', models.DateField(verbose_name='trd')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('payment_term', models.CharField(max_length=50, verbose_name='company')),
                ('product_code', models.CharField(max_length=50, verbose_name='product_code')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_code')),
                ('hs_code', models.CharField(max_length=50, verbose_name='product_code')),
                ('total_contract_qty', models.FloatField(verbose_name='total_contract_qty')),
                ('total_contract_qty_unit', models.CharField(max_length=15, verbose_name='total_contract_qty_unit')),
                ('contract_balance_qty', models.FloatField(verbose_name='contract_balance_qty')),
                ('contract_balance_qty_unit', models.CharField(max_length=15, verbose_name='contract_balance_qty_unit')),
                ('trade_qty', models.FloatField(verbose_name='total_contract_qty')),
                ('trade_qty_unit', models.CharField(max_length=15, verbose_name='total_contract_qty_unit')),
            ],
            options={
                'verbose_name': 'PurchasePending',
                'verbose_name_plural': 'PurchasePendings',
            },
        ),
        migrations.CreateModel(
            name='PurchaseProductTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('total_contract_qty', models.FloatField(null=True)),
                ('trade_qty', models.FloatField(null=True)),
                ('contract_balance_qty', models.FloatField(null=True)),
                ('first_trn', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'PurchaseProductTrace',
                'verbose_name_plural': 'PurchaseProductTraces',
            },
        ),
        migrations.CreateModel(
            name='SalesPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn', models.CharField(max_length=50, verbose_name='trn')),
                ('trd', models.DateField(verbose_name='trd')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('payment_term', models.CharField(max_length=50, verbose_name='company')),
                ('product_code', models.CharField(max_length=50, verbose_name='product_code')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_code')),
                ('hs_code', models.CharField(max_length=50, verbose_name='product_code')),
                ('total_contract_qty', models.FloatField(verbose_name='total_contract_qty')),
                ('total_contract_qty_unit', models.CharField(max_length=15, verbose_name='total_contract_qty_unit')),
                ('contract_balance_qty', models.FloatField(verbose_name='contract_balance_qty')),
                ('contract_balance_qty_unit', models.CharField(max_length=15, verbose_name='contract_balance_qty_unit')),
                ('trade_qty', models.FloatField(verbose_name='total_contract_qty')),
                ('trade_qty_unit', models.CharField(max_length=15, verbose_name='total_contract_qty_unit')),
            ],
            options={
                'verbose_name': 'SalesPending',
                'verbose_name_plural': 'SalesPendings',
            },
        ),
        migrations.CreateModel(
            name='SalesProductTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('total_contract_qty', models.FloatField(null=True)),
                ('trade_qty', models.FloatField(null=True)),
                ('contract_balance_qty', models.FloatField(null=True)),
                ('first_trn', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'SalesProductTrace',
                'verbose_name_plural': 'SalesProductTraces',
            },
        ),
    ]
