# Generated by Django 5.0.7 on 2024-08-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0012_purchasepending_purchaseproducttrace_salespending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial', models.CharField(max_length=10)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
