# Generated by Django 5.0.7 on 2024-08-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0013_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
    ]
