# Generated by Django 5.0.7 on 2024-09-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0015_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepending',
            name='trn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_pending_product', to='trademgt.trade'),
        ),
        migrations.AlterField(
            model_name='salespending',
            name='trn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_pending_product', to='trademgt.trade'),
        ),
    ]
