# Generated by Django 5.0.7 on 2024-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0016_alter_purchasepending_trn_alter_salespending_trn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='selected_currency_rate',
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='selected_currency_rate',
            field=models.FloatField(default=10, verbose_name='selected_currency_rate'),
            preserve_default=False,
        ),
    ]
