# Generated by Django 5.0.7 on 2024-09-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0017_remove_trade_selected_currency_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='as_per_pi_advance',
            field=models.CharField(default=0, max_length=50, verbose_name='as_per_pi_advance'),
            preserve_default=False,
        ),
    ]
