# Generated by Django 5.0.7 on 2024-09-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0018_prepayment_as_per_pi_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepayment',
            name='adv_due_date',
            field=models.DateField(null=True, verbose_name='adv_due_date'),
        ),
    ]
