# Generated by Django 5.0.7 on 2024-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0019_prepayment_adv_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='commission',
        ),
        migrations.AddField(
            model_name='trade',
            name='commission_agent',
            field=models.CharField(default='', max_length=50, verbose_name='commission_agent'),
            preserve_default=False,
        ),
    ]
