# Generated by Django 5.0.7 on 2024-09-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0021_salespurchaseproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespurchase',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='salespurchase',
            name='production_date',
        ),
    ]
