# Generated by Django 5.0.7 on 2024-09-04 16:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0022_remove_salespurchase_batch_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentfinance',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='paymentfinance',
            name='commission_agent_value',
        ),
        migrations.RemoveField(
            model_name='paymentfinance',
            name='production_date',
        ),
        migrations.AddField(
            model_name='paymentfinance',
            name='balance_payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='balance_payment_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentfinance',
            name='commission_value',
            field=models.FloatField(null=True, verbose_name='commission_value'),
        ),
        migrations.AlterField(
            model_name='paymentfinance',
            name='balance_payment',
            field=models.FloatField(null=True, verbose_name='balance_payment'),
        ),
        migrations.AlterField(
            model_name='paymentfinance',
            name='balance_payment_received',
            field=models.FloatField(null=True, verbose_name='balance_payment_received'),
        ),
        migrations.AlterField(
            model_name='paymentfinance',
            name='balance_paymnet_made',
            field=models.FloatField(null=True, verbose_name='balance_paymnet_made'),
        ),
        migrations.AlterField(
            model_name='paymentfinance',
            name='bl_collection_cost',
            field=models.FloatField(null=True, verbose_name='bl_collection_cost'),
        ),
        migrations.AlterField(
            model_name='paymentfinance',
            name='bl_fee',
            field=models.FloatField(null=True, verbose_name='bl_fee'),
        ),
        migrations.AlterField(
            model_name='paymentfinance',
            name='logistic_cost',
            field=models.FloatField(null=True, verbose_name='logistic_cost'),
        ),
        migrations.AlterField(
            model_name='paymentfinance',
            name='net_due_in_this_trade',
            field=models.FloatField(null=True, verbose_name='net_due_in_this_trade'),
        ),
        migrations.CreateModel(
            name='PFCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('charge', models.FloatField(default=0, null=True, verbose_name='charge')),
                ('payment_finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trademgt.paymentfinance', verbose_name='payment_finance')),
            ],
            options={
                'verbose_name': 'PFCharges',
                'verbose_name_plural': 'PFChargess',
            },
        ),
    ]
