# Generated by Django 5.0.7 on 2024-09-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0024_remove_paymentfinance_balance_paymnet_made_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_name')),
                ('batch_number', models.CharField(max_length=50, verbose_name='batch_number')),
                ('production_date', models.DateField(verbose_name='production_date')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=50, verbose_name='unit')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventorys',
            },
        ),
    ]
