# Generated by Django 5.0.7 on 2024-09-10 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0026_currency_packing_productname_shipmentsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='cost_of_packing_per_each',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='markings_in_packaging',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='packaging_supplier',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='rate_in_usd',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='total_packing_cost',
        ),
        migrations.AddField(
            model_name='trade',
            name='commission_value',
            field=models.FloatField(default=100, verbose_name='commission_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='markings_in_packaging',
            field=models.CharField(default='', max_length=100, verbose_name='markings_in_packaging'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='mode_of_packing',
            field=models.CharField(default='', max_length=25, verbose_name='mode_of_packing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='packaging_supplier',
            field=models.CharField(default='', max_length=100, verbose_name='packaging_supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='product_value',
            field=models.FloatField(default=100, verbose_name='product_value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='qty_of_packing',
            field=models.FloatField(default=1, verbose_name='qty_of_packing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='rate_in_usd',
            field=models.FloatField(default=120, verbose_name='rate_in_usd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='rate_of_each_packing',
            field=models.FloatField(default=2, verbose_name='rate_of_each_packing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='total_packing_cost',
            field=models.FloatField(default=2, verbose_name='total_packing_cost'),
            preserve_default=False,
        ),
    ]
