# Generated by Django 5.0.7 on 2024-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0028_paymentterm_advance_from_paymentterm_payment_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='tradeproduct',
            name='commission_rate',
            field=models.FloatField(default=10, verbose_name='commission_rate'),
            preserve_default=False,
        ),
    ]
