# Generated by Django 5.0.7 on 2024-09-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0029_remove_trade_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeproduct',
            name='total_commission',
            field=models.FloatField(default=5, verbose_name='total_commission'),
            preserve_default=False,
        ),
    ]
