# Generated by Django 5.0.7 on 2024-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademgt', '0030_tradeproduct_total_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterm',
            name='advance_within',
            field=models.CharField(max_length=100, verbose_name='advance_within'),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='payment_within',
            field=models.CharField(max_length=100, verbose_name='payment_within'),
        ),
    ]
